### ISSUE TITLE
Update to new version on PyPi

### ISSUE THREAD

**Issue by sebinthomas** [mediapop/datetime_truncate#5]
The datetime_truncate package[1] on PyPi hasn't been updated since 2013 and has many bugs which has since been fixed on master . Could you update PyPi with the latest release ?

[1] [PyPi link ](https://pypi.python.org/pypi/datetime_truncate/1.0.1)

**Comment by kitsunde** [comment]
@gaqzi

**Comment by alfondotnet** [comment]
Same here, the version on PyPi has a reference to `typing` which currently strangely prevents us from upgrading our python version

**Comment by kitsunde** [comment]
I'm happy to review and merge a PR that resolves it.

**Comment by alfondotnet** [comment]
Wouldn't 'the fix' just be creating a new release on PyPi?, I am confused

**Comment by kitsunde** [comment]
Ah, it's a very long time since I needed to publish anything to pypi. I'll see what I can do

**Comment by alfondotnet** [comment]
Thank you @kitsunde !!, much appreciated

**Comment by kitsunde** [comment]
@alfonsoperez Can you elaborate on this `typing` issue? The release on PyPi is 1.1.0 which has all the code on master and there's no reference to `typing` anywhere in this project as far as I can tell.

**Comment by kitsunde** [comment]
Nevermind, I see it now in the published 1.1.0. Fixing it.

**Comment by kitsunde** [comment]
https://pypi.org/project/datetime-truncate/1.1.1/

This should be without `typing`

**Comment by alfondotnet** [comment]
Thanks!!
